### PR TITLE
Fix Cache Duration Variable

### PR DESCRIPTION
**Pull request by evertramos**
Set cache duration value to number.

### CODE REVIEW

**Comment by evertramos** [comment]
I was having some issue as below and found out that here was the issue and fixed for me:

image

**Comment by midnite81** [comment]
Did you set an env key (GEOLOCATION_CACHE)? Or change the config file?

**Comment by evertramos** [comment]
I didn´t set the cache in the env file, once you have the default value on your `./config/geolocation.php`:

```php
'cache-duration' => env('GEOLOCATION_CACHE', '1440'),
```

I kept it as default.

**Comment by midnite81** [comment]
I'm going to decline this merge request as I've implemented your change in a different way. You can composer update to get the latest change.

**Pull request closed without merging**
